### ISSUE TITLE
ToBoolean returns true on too-large stack index

### ISSUE THREAD

**Issue by AlexMax** [Shopify/go-lua#68]
```go
package main

import (
    "fmt"

    "github.com/Shopify/go-lua"
)

func main() {
    l := lua.NewState()
    l.PushBoolean(true)
    l.PushBoolean(false)
    fmt.Printf("Top: %d\n", l.Top())
    for i := 0; i < 4; i++ {
        fmt.Printf("ToBoolean(%d) %t\n", i, l.ToBoolean(i))
    }
}
```

Results in:

```
Top: 2
ToBoolean(0) false
ToBoolean(1) true
ToBoolean(2) false
ToBoolean(3) true
```

That last result is puzzling.

Here's the same sort of thing written in C against PUC-Rio Lua 5.2:

```c
#include <stdio.h>

#include "lua.h"
#include "lauxlib.h"

int main() {
    lua_State *L;
    L = luaL_newstate();
    lua_pushboolean(L, 1);
    lua_pushboolean(L, 0);
    printf("Top: %d\n", lua_gettop(L));
    for (int i = 0; i < 4; i++) {
        printf("ToBoolean(%d) %d\n", i, lua_toboolean(L, i));
    }
}
```

Results in:

```
Top: 2
ToBoolean(0) 0
ToBoolean(1) 1
ToBoolean(2) 0
ToBoolean(3) 0
```

Other **ToWhatever** API's in go-lua appear to have a *value, ok* multi-valued return.  Is the correct fix here to add a second API value, or to simply return `false`?  The former would be consistent with other go-lua API's, the latter would be consistent with the C API and on the surface would not require changing existing code - although this might actually be a downside if there is any code that relies on this peculiarity of out-of-bounds truthiness.

**Comment by nilium** [comment]
Looks like it's an issue with ToBoolean not checking for the case where the value returned by indexToValue is none, so isFalse sees it's not nil and not something false-ish and returns true. Should be easy to fix with something like the following:

```go
func (l *State) ToBoolean(index int) bool {
	val := l.indexToValue(index)
	return val != none && !isFalse(val)
}
```

Not sure yet if that needs a type assertion or anything in particular for the comparison (val != none).

**Comment by nilium** [comment]
This actually surfaces an issue in how `string.find` is implemented in string.go. I'll have more info on that later, but it appears to be fix-able.

**Comment by nilium** [comment]
Alright, got some time to spare. First, I modified isFalse instead of ToBoolean because it was the more appropriate place to make this change:

```diff
 func isFalse(s value) bool {
-	if s == nil {
+	if s == nil || s == none {
 		return true
 	}
 
 	b, isBool := s.(bool)
 	return isBool && !b
 }
```

This appears to be fine from the perspective of tests except for the Lua module tests. When attrib.lua is hit, we end up hitting some correct-by-being-incorrect behavior in string.find and attrib.lua assertions fail for string.find (line 40):

```lua
  assert(not s and string.find(err, "package.path"))
```

This in turn fails because string.find is now interpreting package.path as a pattern, which is obviously unsupported in master and leads to an assert(false). The reason for this is that findHelper on line 28 checks if the fourth argument is true (i.e., forcing the string to be plain). This currently _works_ because ToBoolean on an out of range stack location is none and therefore true. So, to make the ToBoolean correct in that case, we have to ensure that the stack location is valid -- that is, check that it's not TypeNone:

```diff
-	if isFind && (l.ToBoolean(4) || !strings.ContainsAny(p, "^$*+?.([%-")) {
+	isPlain := l.TypeOf(4) == TypeNone || l.ToBoolean(4)
+	if isFind && (isPlain || !strings.ContainsAny(p, "^$*+?.([%-")) {
```

This, in turn, makes findHelper correctly default to true when no argument is passed, allowing attrib.lua to continue passing tests.

So, ToBoolean is wrong _and_ it's wrong enough that it makes something else right.
